-- phpMyAdmin SQL Dump
-- version 2.9.1
-- http://www.phpmyadmin.net
-- 
-- Host: localhost
-- Generation Time: Apr 30, 2012 at 12:14 AM
-- Server version: 5.1.61
-- PHP Version: 5.3.3-7+squeeze8
-- 
-- Database: `vecktorn`
-- 

-- --------------------------------------------------------

-- 
-- Table structure for table `notiser`
-- 

CREATE TABLE `notiser` (
  `notis_id` int(11) NOT NULL AUTO_INCREMENT,
  `vecktor_id` int(11) NOT NULL DEFAULT '0',
  `rubrik` text NOT NULL,
  `text` text NOT NULL,
  `signatur` text NOT NULL,
  `ordning` int(11) NOT NULL DEFAULT '0',
  `skapare` text NOT NULL,
  PRIMARY KEY (`notis_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=2010 ;

-- 
-- Dumping data for table `notiser`
-- 

INSERT INTO `notiser` (`notis_id`, `vecktor_id`, `rubrik`, `text`, `signatur`, `ordning`, `skapare`) VALUES 
(1996, 309, 'F-bilen sjuk', 'F-bilen är sedan ett tag tillbaka lite krasslig, och går därför inte att boka.\r\n\r\nJag och bilen får be att återkomma då den känner sig bättre.', 'Ulf Hörndahl, Bilförman', 1, ''),
(1997, 309, 'Seminars at MAX-lab', 'Jean Susini from European Synchrotron Radiation Facility (ESRF), Grenoble, will hold two seminars at MAX-lab in May. Both will take place in Siberia at Ole Römers väg 1, Lund, at 13:00-14:30.\r\n\r\n7 May 13:00-14:30: The ESRF Upgrade: Challenges for the Instrumentation Programme\r\n\r\n8 May 13:00-14:30: High-Resolution Synchrotron-Based X-Ray Imaging: Trends and Opportunities\r\n\r\nAll are invited.\r\n\r\nMAX IV Laboratory\r\n(via Karin Lilja)', 'Annika Hansdotter, inst. Fysik', 22, ''),
(1998, 309, 'Alkoholhets?', 'Känner du att studentlivet kretsar mycket kring alkohol?\r\nSkulle det vara möjligt att ha en nollning utan alkohol?\r\nBehövs det fler alkoholfria aktiviteter för studenter?\r\n\r\nÄr du också intresserad av att diskutera de normer och attityder som råder kring alkohol i studentlivet och på LTH? Teknologkåren startar nu en alkoholpolitisk grupp för alla studenter på LTH som är intresserade av dessa frågor. Syftet är att skapa ett forum för att diskutera alkoholfrågor och arbeta för att skapa ett mer inkluderande studentliv. Låter det spännande? Hör av dig till Teresia Olsson, vkos@tlth.se.', 'Teresia Olsson, V. Kårordförande', 19, ''),
(1999, 309, 'Säsongsavslutning av Pub Proud', 'Pub Proud - Säsongsavslutning med quiz!\r\n\r\nNu är det äntligen dags för Pub Proud  - en pub för HBTQ-personer och vänner igen. Den 3 maj från klockan 17 är ni hjärtligt välkomna till Cornelis, Kårhuset. Som vanligt serveras mat och dryck i trevlig atmosfär. Då det även är säsongsavslutning slår vi till med quiz! Quizet börjar klockan 18 och lag anmäles på plats innan dess. Mer information kan hittas på www.tlth.se/pubproud. Alla studenter som är medlemmar i Teknologkåren eller AF är välkomna. För frågor kontakta, aktsam@tlth.se. Välkommen!', 'Johan Edentoft, Aktivitetssamordnare', 11, ''),
(2000, 309, 'Spännande föredrag på Fysik', 'Tisdag 2012-04-24 "Scholarship of teaching and learning", Ann-Marie Pendrill (Föreståndare för Nationellt Resurscentrum för Fysik, http://www.fysik.org) Fysicum, sal B, kl 15.30\r\n\r\nTisdag 2012-04-24 Chemical imaging and Nano-ARPES at Synchrotron SOLEIL: A new concept in scanning photoelectron microscopy, Seminar at MAX-lab, http://www.lth.se/index.php?id=63573\r\n\r\nOnsdag 2012-04-25 Clickers/röstningssystem i undervisningen, CED i samarbete med Fysiska institutionen, seminarium/workshop, http://www.lth.se/fileadmin/fysik/Gemensam_personal/Nyhetsbrev/Seminarium_om_clickers_i_undervisningen.pdf\r\n\r\n2012-05-14 + 2012-05-15 Crafoorddagarna, http://www.crafoordprize.se\r\n\r\nTisdag 2012-05-15 "Joint Colloquium: Quantum Physics in Superconducting Circuits: Dynamical Casimir Effect and Artifical Atoms", Per Delsing (Chalmers Nanotechnology Center, http://www.chalmers.se/ap/nano-en), Fysicum, sal B, kl 15.30\r\n\r\n2012-05-24 Honorary Doctors´ Seminar Programme 2012, Naturvetenskapliga fakulteten, http://www.naturvetenskap.lu.se/om-fakulteten/hedersdoktorer', 'Knut Deppert, inst. Fysik', 21, ''),
(2001, 309, 'Studierådets Stormöte', 'Är du sugen på att vara med och påverka din utbildning och studiesituation här på LTH? Om svaret är ja kom du på studierådets stormöte imorgon (24 April) klockan 12 i MH:B. På mötet ska vi välja in folk till programledningarna för F, Pi och N. Programledningarna har ansvar för att programmen utvecklas. I varje programledning sitter 6 studenter så här finns det många som kan samarbeta tillsammans för att genomföra saker.\r\n\r\nDet finns också platser i olika institutionsstyrelser. Här sitter man med i institutionens styrelse och får vara med bland annat när man sätter budget, pratar rekrytering av lärare och mycket mer. Det brukar även diskuteras en hel del grundutbildning i dessa organ. Här sitter man oftast ensam från sektionen men det sitter andra studenter här också. \r\n\r\nDe institutionsstyrelser som vi har platser till är (inom parantes antal platser)\r\nFysiska institutionen (2)\r\nMatematikcentrum (1)\r\nMätteknik och industriell elektroteknik (1)\r\n\r\nSå kom imorgon lunch och kandidera till en post!\r\n\r\nHar du någon fråga får du gärna kontakta mig på um@fsek.lth.se.', 'Johan Westerborn, Utbildningsm.', 2, ''),
(2002, 309, 'Caféfest', 'Den 3e maj går årets tackfest av stapeln. Du har väl inte glömt anmäla dig via mailet? Känner du nu att du saknar mail från caféet kan det bero på att du inte jobbat tre gånger än! Men frukta icke, tid finns ännu att hinna jobba i caféet, in och skriv upp dig idag!\r\n\r\nOm du tror att du borde fått ett anmälningsmail men inte fått det så tveka inte att kontakta cafémästeriet!', 'Linus Hammarlund, Cafémästare', 3, ''),
(2003, 309, 'Nanobranschkväll', 'Nu är det dags för årets evenemang för alla er som är intresserade av nanobranschen, nämligen nanobranschkvällen!\r\n\r\nDet går att anmäla sig på sektionens hemsida och på Arbetslivsutskottets anslagstavla.\r\n\r\nDen 26 april i MH:A kommer 4 föredragshållare att prata om nanoteknik. I nuläget är dessa föredrag/företag bokade: \r\nJohan Borgström - projektledare för nano update i Helsingborg - kommer bland annat att prata om nanoföretag i regionen och hur nanobranschen ser ut i dagsläget\r\nTheodor Nielsen från NIL Technology - specialiserade på nanopatterning och nano imprint lithography, kommer även prata lite om hur det är att starta företag\r\nGenovis - biomedicinföretag som bland annat använder unika enzym för att utveckla och kvalitetssäkra läkemedel\r\nqunano - gör halvledarmaterial på nanoskalan \r\n\r\nFörsta föredraget börjar klockan 17.29, kom i tid. Under kvällen kommer mat serveras för de som skrivit upp sig på en anmälningslista. Denna lista kommer dyka upp utanför Hilbert nästa vecka. Eventet finns på facebook, där informationen uppdateras kontinuerligt, sök på Nanobranschkväll 2012. \r\n\r\nNanobranschkvällen är inte bara för de som läser nano utan för alla som är intresserade, så tveka inte att titta förbi och bli inspirerad!', 'Mattias Kroon, Arbetslivsansvarig', 5, ''),
(2004, 309, 'Brunch och bio med Tetra Pak', 'Hur ser din drömarbetsplats ut?\r\nTetra Pak behöver dina tankar, funderingar  och åsikter \r\nför att vi ska kunna bygga framtidens arbetsplats! \r\nPå vilket sätt vill du arbeta? Vilka miljöer skulle \r\nvara optimala för dig? Tetra Pak vill skapa den \r\nbästa möjliga miljön för våra anställda och inte \r\nminst för framtidens anställda och de behöver din \r\nhjälp. Som tack bjuder de på brunch och två biobiljetter.\r\n\r\nNär? Den 10 maj kl 9-12 + brunch. \r\nVar? Hos Tetra Pak\r\nAnmäl dig till; IK@fsek.lth.se', 'Mattias Kroon, Arbetslivsansvarig', 6, ''),
(2005, 309, 'Sekreteraren Raljerar', 'Hejsan hoppsan F-sektionen!\r\n\r\nOuaaaah! Efter det här raljerandet är det endast två kvar innan jag lämnar min post. Sen är det sommar, eller nja nästan. \r\nDet är den lilla detaljen att det ska tentas också! Sitter skrivande stund och lyssnar på Birdland med Maynard Ferguson,\r\ndetta får mina fingar att minnas min saxofon därhemma och ett sug som gömt sig långt in i ryggmärgen sipprar ut och har \r\nsnart fyllt min kropp från topp och tå! Tror jag ska ta en trudilutt någon dag då jag hinner hem i vettig tid!\r\n\r\nMed värmen här (ja, det börjar banne mig bli varmt nue) kommer också en härlig skadeglädje mot de som bor i stockholm \r\nsom klarar över snö och kyla. Hihihihihi.\r\n\r\nTänk på ljudet av en cola-burk som öppnas. Det lilla fräsandet som kommer från kolsyran, kylan av den iskalla drycken i din hand.\r\n\r\nFörsta klunken.', 'Staffan Hedström, Sekreterare', 29, ''),
(2006, 309, 'Workshop i Retorik', 'påTisdag bjuder in till en kväll i talets tecken. Professor i retorik, Anders Sigrell håller en inspirerande föreläsning för oss tunghäftade teknologer kl.17.15 i MH:A nu på tisdag. Efter föreläsningen får de som vill prova på talarpodiets magi. \r\nLyssna, lär och utvecklas!', 'Malin Alsved, vice KM', 4, ''),
(2007, 309, 'Funktionärstack', 'Är du en av alla oss om får F-sektionen att vara den mesta och bästa sektionen vid LTH? Då ska du får vad du förtjänar - ett stort Tack! \r\n\r\nDet blir en utflykt till Lomma beach (Sveriges Miami) där vi har volleybollturnering, spelar fotboll, kubb, badar och kastar sand på varandra. Det kommer att bjudas av läckerheter runt en stor picknickfilt! Vi har valt en solig dag för att det ska bli så mycket roligare, och en dag när de flesta tentor är avklarade, närmare bestämt torsdagen den 31 maj. Bussen kommer att avgå vid 11 på förmiddagen och köra tillbaka vid 16. Vill man cykla får man gärna göra det (då är man ju desto hungrigare när man kommer fram till picknickbuffén).\r\n\r\nAlla troget engagerade funktionärer kommer att få ett mail i veckan där man kan anmäla sig (hela utflykten är gratis).', 'Malin Alsved, vice KM', 7, ''),
(2008, 309, 'Stjärnpostval', 'Nu börjar det bli dags för styrelsen att genomföra stjärnpostval för nästa läsår. De poster som skall tillsättas nu i vår är:\r\n\r\n* Redaktionsmedlem i von Tänen\r\n* Spindelman\r\n* Ledamot i studierådet för [F, pi, n]\r\n\r\nHör av dig till respektive utskottsordförande för att få information om hur man gör för att kandidera till poster. Det är roligt att engagera sig!', 'Johan Förberg, Valberedningen', 5, ''),
(2009, 309, 'Veckans Sanning', 'Ikväll har det varit Valfullmäktige på Kåren, där flera av heltidarposterna inför nästa läsår har tillsatts. Valberedningen på Kåren presenterade bland annat statistik som ställer det utom allt tvivel att F-are är bättre än andra. Tyvärr tyckte man inte att det fanns tillräckligt underlag för att välja en ny kårstyrelse, varför styrelsen vakantsattes i sin helthet. Kommer vi få klara oss utan kårstyrelse i höst? Missa inte den rafflande upplösningen!\r\n\r\nNu närmst väntar JubelOFF för de som engagerade sig i jubiléet, samt Tandemkickoff på onsdag för de som lyckades roffa åt sig en Tandembiljett.\r\n\r\nImorgon är det biljettsläpp för den manliga halvan (skrock, skrock) av F-sektionen. Biljetter till killsittningen kommer släppas under lunchen. Intresserade bör hålla sig framme eftersom biljetterna väntas ta slut ganska fort.\r\n\r\nAnnars rullar sektionslivet på som vanligt. På lördag kommer Datasektionen hålla jubileumsbankett med anledning av att sektionen fyller 30 år.\r\n\r\nStyrelsemöte kommer hållas på onsdag, kl. 12 på Mattehusets tredje våning. Alla intresserade välkomnas att närvara.\r\n\r\nOch just det, våren är här! (igen). Klart slut från sanningsministern.', 'Johan Förberg, Sanningsminister', 30, '');
